# Generated by Django 2.2.14 on 2021-02-19 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogProduct',
            new_name='Blog',
        ),
    ]
