# Generated by Django 2.2.14 on 2021-03-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeBlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sst1',
            field=models.ImageField(blank=True, upload_to='homeBlog/images'),
        ),
        migrations.AddField(
            model_name='project',
            name='sst2',
            field=models.ImageField(blank=True, upload_to='homeBlog/images'),
        ),
        migrations.AddField(
            model_name='project',
            name='sst3',
            field=models.ImageField(blank=True, upload_to='homeBlog/images'),
        ),
        migrations.AddField(
            model_name='project',
            name='sst4',
            field=models.ImageField(blank=True, upload_to='homeBlog/images'),
        ),
        migrations.AddField(
            model_name='project',
            name='sst5',
            field=models.ImageField(blank=True, upload_to='homeBlog/images'),
        ),
        migrations.AddField(
            model_name='project',
            name='url10',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='url42',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='url72',
            field=models.URLField(blank=True),
        ),
    ]
