# Generated by Django 2.2.14 on 2021-03-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeBlog', '0002_auto_20210310_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
