# Generated by Django 3.1.7 on 2021-03-17 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeBlog', '0003_project_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view', models.TextField(default=None)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='view',
        ),
    ]
