# Generated by Django 3.1.7 on 2021-03-17 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeBlog', '0004_auto_20210318_0248'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IpUser',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='view',
            new_name='user',
        ),
    ]
